# -*- coding: utf-8 -*-
"""Bias&varianceTradeoff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UvClNGR6sO63llGaNgvF0jbkJ4CBpDu
"""

from matplotlib import pyplot as plt
import numpy as np

# Simulating Bias-Variance Tradeoff

# Model complexity range (e.g., degree of polynomial)
complexity = np.linspace(1, 10, 100)

# Hypothetical curves (simplified and smoothed)
bias_squared = np.exp(-0.5 * complexity) * 0.5
variance = np.exp(0.5 * (complexity - 5)) / (np.exp(0.5 * (complexity - 5)) + 5)
noise = np.ones_like(complexity) * 0.1
total_error = bias_squared + variance + noise

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(complexity, bias_squared, label='Bias²', linewidth=2)
plt.plot(complexity, variance, label='Variance', linewidth=2)
plt.plot(complexity, total_error, label='Total Error', linewidth=2, linestyle='--')
plt.plot(complexity, noise, label='Irreducible Error', linestyle=':', linewidth=2)
plt.xlabel("Model Complexity")
plt.ylabel("Error")
plt.title("Bias-Variance Tradeoff")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

